import numpy as np
import scipy

from .DiscreteD import DiscreteD
from .GaussD import GaussD



class HMM:
    """
    HMM - class for Hidden Markov Models, representing
    statistical properties of random sequences.
    Each sample in the sequence is a scalar or vector, with fixed DataSize.
    
    Several HMM objects may be collected in a single multidimensional array.
    
    A HMM represents a random sequence(X1,X2,....Xt,...),
    where each element Xt can be a scalar or column vector.
    The statistical dependence along the (time) sequence is described
    entirely by a discrete Markov chain.
    
    A HMM consists of two sub-objects:
    1: a State Sequence Generator of type MarkovChain
    2: an array of output probability distributions, one for each state
    
    All states must have the same class of output distribution,
    such as GaussD, GaussMixD, or DiscreteD, etc.,
    and the set of distributions is represented by an object array of that class,
    although this is NOT required by general HMM theory.
    
    All output distributions must have identical DataSize property values.
    
    Any HMM output sequence X(t) is determined by a hidden state sequence S(t)
    generated by an internal Markov chain.
    
    The array of output probability distributions, with one element for each state,
    determines the conditional probability (density) P[X(t) | S(t)].
    Given S(t), each X(t) is independent of all other X(:).
    
    
    References:
    Leijon, A. (20xx) Pattern Recognition. KTH, Stockholm.
    Rabiner, L. R. (1989) A tutorial on hidden Markov models
    	and selected applications in speech recognition.
    	Proc IEEE 77, 257-286.
    
    """
    def __init__(self, mc, distributions):

        self.stateGen = mc
        self.outputDistr = distributions

        self.nStates = mc.nStates
        self.dataSize = distributions[0].dataSize
    
    def rand(self, nSamples):
        """
        [X,S]=rand(self,nSamples); generates a random sequence of data
        from a given Hidden Markov Model.
        
        Input:
        nSamples=  maximum no of output samples (scalars or column vectors)
        
        Result:
        X= matrix or row vector with output data samples
        S= row vector with corresponding integer state values
          obtained from the self.StateGen component.
          nS= length(S) == size(X,2)= number of output samples.
          If the StateGen can generate infinite-duration sequences,
              nS == nSamples
          If the StateGen is a finite-duration MarkovChain,
              nS <= nSamples
        """
        
        #*** Insert your own code here and remove the following error message 
        S = self.stateGen.rand(nSamples)
        Xlist = []
        for s in S:
            Xlist.append(self.outputDistr[s].rand(1))
        X = np.hstack(Xlist)
        return X, S

        
    def viterbi(self, X):
        log_pX = self.calcPx(X)
        pX = np.exp(log_pX)
        chi = np.zeros((self.nStates, pX.shape[1]))
        zeta = np.zeros((self.nStates, pX.shape[1]), dtype=int)
        chi[:, 0] = self.stateGen.q * pX[:, 0]
        for t in range(1, pX.shape[1]):
            for s in range(self.nStates):
                chi[s, t] = np.max(chi[:, t-1] * self.stateGen.A[:, s]) * pX[s, t]
                zeta[s, t] = np.argmax(chi[:, t-1] * self.stateGen.A[:, s])
        S = np.zeros(pX.shape[1], dtype=int)
        S[-1] = np.argmax(chi[:, -1])
        for t in range(pX.shape[1]-2, -1, -1):
            S[t] = zeta[S[t+1], t+1]
        return S


    def train(self, X):
        T = X.shape[1]
        D = X.shape[0]
        eta = np.eye(D)*1e-3
        log_diff = np.inf
        prev_log_prob = -np.inf
        while log_diff > 1e-6:
            log_prob, log_alpha, log_beta, log_pX = self.logprob(X)
            log_gamma = log_alpha + log_beta
            log_gamma -= scipy.special.logsumexp(log_gamma, axis=0, keepdims=True)
            gamma = np.exp(log_gamma)
            log_xi = np.zeros((T-1, self.nStates, self.nStates))
            for t in range(T-1):
                log_xi[t] = log_alpha[:, t][:,None] + np.log(self.stateGen.A + 1e-300) + log_pX[:, t+1] + log_beta[:, t+1]
            xi = np.exp(log_xi - scipy.special.logsumexp(log_xi, axis=(1,2), keepdims=True))
            self.stateGen.q = gamma[:, 0] / np.sum(gamma[:, 0])
            #Prevent division by zero
            den = np.maximum(np.sum(gamma[:,:-1], axis=1), 1e-10)
            num = np.sum(xi, axis=0)
            A_new = np.zeros_like(self.stateGen.A)
            for i in range(self.nStates):
                for j in range(self.nStates):
                    A_new[i, j] = num[i, j] / den[i]
            A_new /= np.sum(A_new, axis=1, keepdims=True)
            self.stateGen.A = A_new

            for s in range(self.nStates):
                weights = gamma[s,:]
                weights /= np.sum(weights)
                mu = np.sum(X * weights, axis=1, keepdims=True)
                self.outputDistr[s].means = mu.flatten()
                diff = X - mu
                cov = diff @ (diff * weights).T + eta
                self.outputDistr[s].cov = cov
            log_diff = np.abs(log_prob - prev_log_prob)
            if not np.isfinite(log_prob):
                raise ValueError("Log probability became non-finite")
            prev_log_prob = log_prob
            print(f"Log-likelihood: {log_prob}, Log-likelihood difference: {log_diff}")
        return log_prob

            


            

    def stateEntropyRate(self):
        pass

    def setStationary(self):
        pass

    def logprob(self, X):
        eps = 1e-300
        log_pX= self.calcPx(X)
        log_alpha = self.stateGen.forward(log_pX)        
        log_beta = self.stateGen.backward(log_pX)
        log_prob = scipy.special.logsumexp(log_alpha[:, -1])
        return log_prob, log_alpha, log_beta, log_pX

    def calcPx(self, X):
        log_pX = np.zeros((self.nStates, X.shape[1]))
        
        for t in range(X.shape[1]):
            for s in range(self.nStates):
                log_pX[s,t] = self.outputDistr[s].logprob(X[:, t])
        return log_pX

    def adaptStart(self):
        pass

    def adaptSet(self):
        pass

    def adaptAccum(self):
        pass