import numpy as np

from .DiscreteD import DiscreteD
from .GaussD import GaussD



class HMM:
    """
    HMM - class for Hidden Markov Models, representing
    statistical properties of random sequences.
    Each sample in the sequence is a scalar or vector, with fixed DataSize.
    
    Several HMM objects may be collected in a single multidimensional array.
    
    A HMM represents a random sequence(X1,X2,....Xt,...),
    where each element Xt can be a scalar or column vector.
    The statistical dependence along the (time) sequence is described
    entirely by a discrete Markov chain.
    
    A HMM consists of two sub-objects:
    1: a State Sequence Generator of type MarkovChain
    2: an array of output probability distributions, one for each state
    
    All states must have the same class of output distribution,
    such as GaussD, GaussMixD, or DiscreteD, etc.,
    and the set of distributions is represented by an object array of that class,
    although this is NOT required by general HMM theory.
    
    All output distributions must have identical DataSize property values.
    
    Any HMM output sequence X(t) is determined by a hidden state sequence S(t)
    generated by an internal Markov chain.
    
    The array of output probability distributions, with one element for each state,
    determines the conditional probability (density) P[X(t) | S(t)].
    Given S(t), each X(t) is independent of all other X(:).
    
    
    References:
    Leijon, A. (20xx) Pattern Recognition. KTH, Stockholm.
    Rabiner, L. R. (1989) A tutorial on hidden Markov models
    	and selected applications in speech recognition.
    	Proc IEEE 77, 257-286.
    
    """
    def __init__(self, mc, distributions):

        self.stateGen = mc
        self.outputDistr = distributions

        self.nStates = mc.nStates
        self.dataSize = distributions[0].dataSize
    
    def rand(self, nSamples):
        """
        [X,S]=rand(self,nSamples); generates a random sequence of data
        from a given Hidden Markov Model.
        
        Input:
        nSamples=  maximum no of output samples (scalars or column vectors)
        
        Result:
        X= matrix or row vector with output data samples
        S= row vector with corresponding integer state values
          obtained from the self.StateGen component.
          nS= length(S) == size(X,2)= number of output samples.
          If the StateGen can generate infinite-duration sequences,
              nS == nSamples
          If the StateGen is a finite-duration MarkovChain,
              nS <= nSamples
        """
        
        #*** Insert your own code here and remove the following error message 
        S = self.stateGen.rand(nSamples)
        Xlist = []
        for s in S:
            Xlist.append(self.outputDistr[s].rand(1))
        X = np.hstack(Xlist)
        return X, S

        
    def viterbi(self, X):
        pX, _ = self.calcPx(X)
        chi = np.zeros((self.nStates, pX.shape[1]))
        zeta = np.zeros((self.nStates, pX.shape[1]), dtype=int)
        chi[:, 0] = self.stateGen.q * pX[:, 0]
        for t in range(1, pX.shape[1]):
            for s in range(self.nStates):
                chi[s, t] = np.max(chi[:, t-1] * self.stateGen.A[:, s]) * pX[s, t]
                zeta[s, t] = np.argmax(chi[:, t-1] * self.stateGen.A[:, s])
        S = np.zeros(pX.shape[1], dtype=int)
        S[-1] = np.argmax(chi[:, -1])
        for t in range(pX.shape[1]-2, -1, -1):
            S[t] = zeta[S[t+1], t+1]
        return S


    def train(self, X):
        eta = np.eye(self.nStates)*1e-3
        log_diff = np.inf
        prev_log_prob = -np.inf
        while log_diff > 1e-6:
            num_total = np.zeros((self.nStates, self.nStates))
            den_total = np.zeros(self.nStates)
            means_total = np.zeros((self.nStates, self.dataSize))
            cov_total = np.zeros((self.nStates, self.dataSize, self.dataSize))
            q_total = np.zeros(self.nStates)
            gamma_sum = np.zeros(self.nStates)
            gammas = []
            log_prob_total = 0.0

            for seq in X:
                T = seq.shape[1]
                log_prob, a_hat, b_hat, c, pX = self.logprob(seq)
                gamma = a_hat * b_hat
                e = np.zeros((T-1, self.nStates, self.nStates))
                for t in range(T-1):
                    for i in range(self.nStates):
                        for j in range(self.nStates):
                            e[t, i, j] = a_hat[i, t] * self.stateGen.A[i, j] * pX[j, t+1] * b_hat[j, t+1] / c[t+1]
                    e[t] /= np.maximum(np.sum(e[t]), 1e-300)
                gamma /= np.sum(gamma, axis=0, keepdims=True)
                gammas.append(gamma)
                q_total += gamma[:, 0]
                #Prevent division by zero
                den_total += np.maximum(np.sum(gamma[:,:-1], axis=1), 1e-10)
                num_total += np.sum(e, axis=0)
                for s in range(self.nStates):
                    gamma_sum[s] += np.sum(gamma[s])
                    means_total[s] += np.sum(seq * gamma[s], axis=1)
                log_prob_total += log_prob

            A_new = np.zeros_like(self.stateGen.A)
            for i in range(self.nStates):
                for j in range(self.nStates):
                    A_new[i, j] = num_total[i, j] / den_total[i]
            
            A_new /= np.sum(A_new, axis=1, keepdims=True)
            self.stateGen.A = A_new
            self.stateGen.q = q_total / len(X)

            for s in range(self.nStates):
                self.outputDistr[s].means = means_total[s] / np.maximum(gamma_sum[s], 1e-300)
        
            for i, seq in enumerate(X):
                for s in range(self.nStates):
                    diff = seq - self.outputDistr[s].means[:, np.newaxis]
                    cov_total[s] += (diff * gammas[i][s]) @ diff.T
            for s in range(self.nStates):
                self.outputDistr[s].cov = cov_total[s] / np.maximum(gamma_sum[s], 1e-300) + eta
            log_diff = np.abs(log_prob_total - prev_log_prob)
            prev_log_prob = log_prob_total
            print(f"Log-likelihood: {log_prob_total}, Log-likelihood difference: {log_diff}")
        return log_prob_total

            


            

    def stateEntropyRate(self):
        pass

    def setStationary(self):
        pass

    def logprob(self, X):
        pX, log_scale = self.calcPx(X)
        a_hat, c = self.stateGen.forward(pX)
        
        b_hat = self.stateGen.backward(c, pX)
        if self.stateGen.is_finite:
            log_prob = np.sum(np.log(c)) + log_scale
        else:
            log_prob = np.sum(np.log(c[:-1])) + log_scale
        return log_prob, a_hat, b_hat, c, pX

    def calcPx(self, X):
        pX = np.zeros((self.nStates, X.shape[1]))
        log_scale = 0.0
        for t in range(X.shape[1]):
            probs = []
            for s in range(self.nStates):
                probs.append(self.outputDistr[s].prob(X[:, t]))
            probs = np.array(probs)
            scale = np.max(probs)
            if scale > 0:
                probs = probs / scale
                log_scale += np.log(scale)
            
            pX[:, t] = probs
        return pX, log_scale

    def adaptStart(self):
        pass

    def adaptSet(self):
        pass

    def adaptAccum(self):
        pass